ingress:
  path: /firefox
  affinity: false
  
persistence:
  enabled: false

autoscaling:
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80