name: Build and Deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: Poooley/K8s.Pipelines/Build.NET@main
      with:
        PROJECT_PATH: /
        SERVICE_NAME: "nginx-manifestupdater"
        DOCKER_TOKEN: ${{ secrets.ACTION_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: Poooley/K8s.Pipelines/Deploy.NET@main
      with:
        SERVICE_NAME: "nginx-manifestupdater"
        VALUES_FILE: "./values.yaml"
        DOCKER_TOKEN: ${{ secrets.ACTION_TOKEN }}
        KUBECONFIG: ${{ secrets.KUBECONFIG }}